MarketApp.webUI/ViewModels/ProductViewModel.cs
using MarketApp.webUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarketApp.webUI.ViewModels
{
    public class ProductViewModel
    {
        public List<Product> Products { get; set; }
    }
}

MarketApp.webUI/Controllers/AdminController.cs
using MarketApp.Business.Abstract;
using MarketApp.Entity;
using MarketApp.webUI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace MarketApp.webUI.Controllers
{
    [Authorize(Roles ="admin")]
    public class AdminController : Controller
    {
        private IProductService _productService;
        private ICategoryService _categoryService;
        public AdminController(IProductService productService, ICategoryService categoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
        }
        //Product işlemleri
        public IActionResult ProductList()
        {
            
            return View(new ProductListModel
            { 
            Products = _productService.GetAll()
            });
        }
        [HttpGet]
        public IActionResult CreateProduct()
        {
            return View(new ProductModel());
        }
        [HttpPost]
        public IActionResult CreateProduct(ProductModel model)
        {

            if (ModelState.IsValid) // ProductModel'den oluşturulan kopyada girilen veriler kurallara uygun biçimde geldi ise true döner.
            {
                var entity = new Product()
                {
                    Name = model.Name,
                    Price = model.Price,
                    Description = model.Description,
                    ImgUrl = model.ImgUrl
                };
                _productService.Create(entity); // oluşturma işlemi db'de yapılır.

                return RedirectToAction("ProductList"); //Ekleme işleminden sonra ProductList'e yönlendirilerek direkt ürün listesiyle karşılaşılır.

            }
            return View(model); // Doğrulama işlemi hatalı olursa tekrar aynı sayfaya döndürülür.

        }
        public IActionResult EditProduct(int? id)
        {
            if(id == null) // herhangi bir id bilgisi gelmezse
            {
                return NotFound();
            }
            // 
            var entity = _productService.GetByIdWithCategories((int)id); // id gelirse nullable tipinden int'e çevrilmeli 
            if (entity == null)
            {
                return NotFound(); // olmayan ürüne işlem yapılamayacağından dolayı.
            }
            var model = new ProductModel()
            {
                Id = entity.Id,
                Name = entity.Name,
                Price = entity.Price,
                Description = entity.Description,
                ImgUrl = entity.ImgUrl,
                SelectedCategories = entity.ProductCategories.Select(i => i.Category).ToList() //seçili olan kategori bilgileri
            };
            ViewBag.Categories = _categoryService.GetAll(); // DB'deki tüm kategorileri getirir.
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> EditProduct(ProductModel model, int[] categoryIds, IFormFile file) // seçili olan kategori dizi şeklinde alınır.
        {                                                                                       // "file" = inputtan gelen control name
            if(ModelState.IsValid)
            {
                var entity = _productService.GetById(model.Id);
                if (entity == null)
            {
                return NotFound();
            }
            entity.Name = model.Name;
            entity.Price = model.Price;
            entity.Description = model.Description;
            
            if (file != null)
            {
                entity.ImgUrl = file.FileName;

                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", file.FileName); //Root dizinindeki image klasörünün yolu gösterildi, kullanılacak isime göre arama yapıp ekler

                    using (var stream = new FileStream(path, FileMode.Create)) //pathe resmin gönderilmesi
                    {
                        await file.CopyToAsync(stream);
                    }
            }

                _productService.Update(entity, categoryIds); // güncelleme db'de işlemi yapılır

            return RedirectToAction("ProductList");
                // url'ye değil de Rout'a yönlendirme işlemi yapıldı. güncellemeden sonra kullanıcı index'e gönderilir
                // ProductList'e karşılık gelen Url, Rout içerisinden alınacak.
            }
            else
            {
                ViewBag.Categories = _categoryService.GetAll(); // DB'deki tüm kategorileri getirir.
                return View(model);
            }
        }
        [HttpPost]
        public IActionResult DeleteProduct(int productId)
        {
            var entity = _productService.GetById(productId);
            if (entity != null)
            {
                _productService.Delete(entity);
            }
            return RedirectToAction("ProductList");
        }
        // Kategori işlemleri
        public IActionResult CategoryList()
        {
            return View(new CategoryListModel()
             {
                Categories = _categoryService.GetAll()
            });
        }
        [HttpGet]
        public IActionResult EditCategory(int id)
        {
            var entity = _categoryService.GetByIdWithProducts(id); // id gönderiyoruz, bize bir kategori bilgisi geliyor
            // onun yanında da o kategoriye ait olan ürünler geliyor. 

            return View(new CategoryModel() 
            {
                Id = entity.Id,             // Db'den gelen Id ve Name Model olarak sayfaya gönderilir.
                Name = entity.Name,
                Products = entity.ProductCategories.Select(p=>p.Product).ToList()
            });
           
        }
        [HttpPost]
        public IActionResult EditCategory(CategoryModel model)
        {
            var entity = _categoryService.GetById(model.Id);
            if (entity ==null)
            {                                              
                return NotFound(); 
            }                                           
            entity.Name = model.Name;                        // Modelden gelen bilgiler db'de güncellenir.
            _categoryService.Update(entity);
            return RedirectToAction("CategoryList");

        }
        [HttpGet]
        public IActionResult CreateCategory()
        {
            
            return View();

        }
        [HttpPost]
        public IActionResult CreateCategory(CategoryModel model)
        {
            var entity = new Category()
            {
                Name = model.Name
            };
            _categoryService.Create(entity);
            return RedirectToAction("CategoryList");

        }
        [HttpPost]
        public IActionResult DeleteCategory(int categoryId)
        {
            var entity = _categoryService.GetById(categoryId);
            if (entity != null)
            {
                _categoryService.Delete(entity);
            }
            return RedirectToAction("CategoryList");

        }
        [HttpPost]
        public IActionResult DeleteFromCategory(int categoryId, int productId) // hangi kategorideki hangi ürün
        {
            _categoryService.DeleteFromCategory(categoryId, productId);
            return Redirect("/admin/editcategory/"+categoryId); //editcategory'e istediği parametre gönderilir.
        }

    }
}

MarketApp.webUI/Controllers/SepetController.cs
using MarketApp.Business.Abstract;
using MarketApp.webUI.Identity;
using MarketApp.webUI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarketApp.webUI.Controllers
{   
    [Authorize]
    public class SepetController : Controller
    {
        private ISepetService _sepetService;
        private UserManager<UserIdentity> _userManager;
        public SepetController(ISepetService sepetService, UserManager<UserIdentity> userManager)
        {
            _sepetService = sepetService;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var sepet = _sepetService.GetSepetByUserId(_userManager.GetUserId(User)); // User bilgisine göre userId getirilecek.
            return View(new SepetModel()
            { 
                SepetId = sepet.Id, 
                SepetItems = sepet.SepetItems.Select(i=> new SepetItemModel()
                {
                    SepetItemId =i.Id,
                    ProductId = i.Product.Id,
                    Name = i.Product.Name,
                    Price = (double)i.Product.Price,   //
                    ImageUrl = i.Product.ImgUrl,
                    Quantity = i.Quantity

                }).ToList()
            });
        }
        [HttpPost]
        public IActionResult AddToCart(int productId, int quantity)
        {
            _sepetService.AddToChart(_userManager.GetUserId(User), productId, quantity);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult DeleteFromCart(int productId)
        {
            _sepetService.DeleteFromCart(_userManager.GetUserId(User), productId);
            return RedirectToAction("Index");
        }
    }
}

MarketApp.webUI/Controllers/UserController.cs
using MarketApp.DataAccess.Abstract;
using MarketApp.Entity;
using MarketApp.webUI.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarketApp.webUI.Controllers
{
    public class UserController : Controller
    {
        private IProductRepository _productService;
        public UserController(IProductRepository productService)
        {
            _productService = productService;
        }
        public IActionResult Details(int? id)
        {
            if (id == null) // herhangi bir id değeri girilmemiş ise hata döndürür.
            {
                return NotFound();
            }
            Product product = _productService.GetProductDetails((int)id);
            if (product == null)    // alınan id değerine karşılık bir ürün bulunamamışsa hata döndürür.
            {
                return NotFound();
            }
            return View(new ProductDetailsModel()   // id değeri bulunan ürün categori bilgisiyle gönderilir.
                {
                Product = product,
                Categories = product.ProductCategories.Select(i=>i.Category).ToList()
            }); 
        }
        public IActionResult List(string category, int page=1)     // Tüm kayıtlar listelenir.
        {                                                          //sayfa numarası varsayılan olarak 1 verildi.
            const int pageSize = 6; // bir sayfada bulunacak ürün adedi.
            return View(new ProductListModel()
            {
                PageInfo = new PageInfo()
                {
                    TotalProducts = _productService.GetCountByCategory(category),
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    CurrentCategory=category
                },
                Products = _productService.GetProductsByCategory(category, page, pageSize)  
            }) ;
        }
    }
}

MarketApp.webUI/ViewComponents/CategoryListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MarketApp.Business.Abstract;
using MarketApp.webUI.Models;

namespace MarketApp.webUI.ViewComponents
{
    public class CategoryListViewComponent:ViewComponent
    {
        private ICategoryService _categoryService;
        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public IViewComponentResult Invoke()
        {
            //Tüm category bilgileri view' e taşınır.
            return View(new CategoryListViewModel()
            { 
                SelectedCategory = RouteData.Values["category"]?.ToString(), // null olan bir değer stringe çevrilemediğinden dolayı null olup olmadığı "?" ile sorgulanır.
                Categories = _categoryService.GetAll()
            });
        }
    }
}

MarketApp.webUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MarketApp.webUI</title>
    <script src="https://kit.fontawesome.com/5264fedd63.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    @RenderSection("MessageBox", false) @*//zorunlu olmasının önüne geçtik*@


    @await Html.PartialAsync("_navbar")
    <div class="row">
        @await Component.InvokeAsync("CategoryList")
    </div>

    <main>
        <div class="container">
            @RenderBody()
        </div>
    </main>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy;
            - <a asp-area="" asp-controller="Home" asp-action="Index">Arif Yusuf Yılmaz && Emin Utku Mert</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MarketApp.webUI/Views/Shared/_jumbotron.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer
<header mb-3>
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">Market App</h1>
            <p class="lead" style="color:red">@_localizer["The New System of Marketing"]</p>
        </div>
    </div>
</header>

MarketApp.webUI/Views/Shared/_navbar.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer
<div class="navbar bg-dark navbar-dark navbar-expand-sm">
    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MarketApp</a>
    <div class="container">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="User" asp-action="List">@_localizer["Products"]</a>
            </li>
            @if (User.Identity.IsAuthenticated)
            {
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Sepet" asp-action="Index">@_localizer["Cart"]</a>
                </li>

                if (User.IsInRole("admin"))
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="CreateProduct">@_localizer["Add Product"]</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="ProductList">@_localizer["Admin Products"]</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="CreateCategory">@_localizer["Add Category"]</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="CategoryList">@_localizer["Admin Categories"]</a>
                    </li>
                }
            }
        </ul>
        <ul class="navbar-nav ml-auto">
            @if (User.Identity.IsAuthenticated)
            {
                if (User.IsInRole("admin"))
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Admin" asp-action="CreateProduct">@User.Identity.Name</a>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Sepet" asp-action="Index">@User.Identity.Name</a>
                    </li>
                }
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Account" asp-action="Logout">@_localizer["Logout"]</a>
                </li>
            }
            else
            {
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Account" asp-action="Login">@_localizer["Login"]</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Account" asp-action="Register">@_localizer["Register"]</a>
                </li>
            }
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("ChangeLanguage","Home", new {returnUrl = Context.Request.Path})">@_localizer["Turkish"]</a>
            </li>
        </ul>
    </div>
</div>

MarketApp.webUI/Views/Shared/_product.cshtml
@model Product
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer
<div class="col-md-4">
    <div class="card mb-3">
        <img src="~/images/@Model.ImgUrl" alt="@Model.Name" class="img-fluid" />
        <div class="card-body">
            <h4 class="card-title">
                <a href="#">@Model.Name</a>
            </h4>
            <small class="text-muted">
                @Model.Price <i class="fas fa-lira-sign"></i>
            </small>
            <div class="card-footer text-center">
                <a asp-controller="User" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-outline-primary btn-sm">@_localizer["Details"]</a>
                @*butona tıklandığında ürün id'sini alır ve User'ın Details action'ını çalıştırır.*@

                @if (User.Identity.IsAuthenticated)@*Login işlemi gerçekleşmişse*@
                {
                    <form asp-controller="Sepet" asp-action="AddToCart" method="post" style="display:inline;">
                        <input type="hidden" name="productId" value="@Model.Id" />
                        <input type="hidden" name="quantity" value="1" />
                        <button type="submit" class="btn btn-outline-primary btn-sm ml-3">@_localizer["Add To Cart"]</button>
                    </form>

                }

            </div>
        </div>
    </div>
</div>